#
# This source file is part of the CS342 2023 Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  desc "Build and test"
  lane :test do
    run_tests(
      code_coverage: true,
      result_bundle: true,
      output_directory: "."
    )
  end

  desc "Build app"
  lane :build do
    build_app
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a beta release to internal TestFlight testers"
  lane :beta do
    signin
    increment_build_number({
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "CS342Application.xcodeproj"
    })
    build
    commit = last_git_commit
    upload_to_testflight(
      distribute_external: true,
      groups: [
        "CS342 Instructors 2023",
        "CS342 Students 2023"
      ],
      submit_beta_review: true,
      notify_external_testers: true,
      changelog: commit[:message]
    )
  end
end
